seed: null
gpu: 0
evaluate: false
data:
    name: hhar
    num_cls: 6
    train_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_a_model_nexus4/finetune/5shot/target/train.pkl
    test_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_a_model_nexus4/finetune/5shot/target/test.pkl
    val_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_a_model_nexus4/finetune/5shot/target/val.pkl
multiprocessing:
    multiprocessing_distributed: false
    workers: 32
    world_size: 1
    rank: 0
    dist_url: tcp://localhost:10002
    dist_backend: nccl
train:
    pretrained: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/230418_target_user_c_model_s3/checkpoint_0099.pth.tar
    optimizer: adam
    criterion: crossentropy
    resume: ''
    epochs: 50
    start_epoch: 0
    batch_size: 4
    lr: 0.0005
    fix_pred_lr: false
    weight_decay: 0
    print_freq: 2
    save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/finetuned/230418_pt_except_user_c_model_s3_finetune_user_a_model_nexus4_shot_5
    cos: false
    schedule: []
test:
    batch_size: 2
    print_freq: 100
model:
    type: cpc
    input_channels: 3
    z_dim: 256
    num_blocks: 5
    num_filters: 256
    seq_len: 30