seed: null
gpu: null
data:
  train_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/pretrain/train.pkl
  test_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/pretrain/test.pkl
  val_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/pretrain/val.pkl
  name: hhar
multiprocessing:
  multiprocessing_distributed: false
  workers: 32
  world_size: 1
  rank: 0
  dist_url: tcp://localhost:10001
  dist_backend: nccl
train:
  task_per_domain: true
  num_task: 5
  task_size: 90
  task_steps: 10
  # 0.001
  task_lr: 0.005
  # momentum: 0.9
  optimizer: adam
  criterion: crossentropy
  # resume: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/test/checkpoint_2000.pth.tar
  resume: ''
  epochs: 1000
  start_epoch: 0
  batch_size: 256
  # 0.001
  lr: 0.001
  fix_pred_lr: false
  weight_decay: 0
  print_freq: 1
  save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/ichar_meta2
  cos: false
  schedule: []
model:
  type: cpc
  input_channels: 3
  z_dim: 256
  num_blocks: 5
  num_filters: 256
  pred_steps: 4
  n_negatives: 15
  offset: 4