seed: null
gpu: 0
data:
  train_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/pretrain/train.pkl
  test_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/pretrain/test.pkl
  val_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/pretrain/val.pkl
  name: hhar
multiprocessing:
  multiprocessing_distributed: false
  workers: 32
  world_size: 1
  rank: 0
  dist_url: tcp://localhost:10001
  dist_backend: nccl
train:
  optimizer: adam
  criterion: crossentropy
  # resume: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/230418_target_user_b_model_nexus4/checkpoint_0499.pth.tar
  resume: ''
  epochs: 100
  start_epoch: 0
  batch_size: 256
  lr: 0.0005 # 0.0005
  fix_pred_lr: false
  weight_decay: 0.001
  print_freq: 100
  save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/ichar_meta
  cos: false
  schedule: []
model:
  type: cpc
  input_channels: 3
  z_dim: 256
  num_blocks: 5
  num_filters: 256
  pred_steps: 4 #12
  n_negatives: 15
  offset: 4 #16
