seed: null
gpu: null
data:
  train_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_b_model_nexus4/pretrain/train.pkl
  test_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_b_model_nexus4/pretrain/test.pkl
  val_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_b_model_nexus4/pretrain/val.pkl
  name: hhar
multiprocessing:
  multiprocessing_distributed: false
  workers: 32
  world_size: 1
  rank: 0
  dist_url: tcp://localhost:10001
  dist_backend: nccl
train:
  task_per_domain: true
  num_task: 10
  task_size: 100
  task_steps: 5
  # 0.001
  task_lr: 0.01
  # momentum: 0.9
  optimizer: adam
  criterion: crossentropy
  # resume: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/test/checkpoint_0999.pth.tar
  resume: ''
  epochs: 1600
  start_epoch: 0
  batch_size: 256
  # 0.001
  lr: 0.001
  fix_pred_lr: false
  weight_decay: 0
  print_freq: 1
  save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/test
  cos: false
  schedule: []
model:
  type: cpc
  input_channels: 3
  z_dim: 256
  num_blocks: 5
  num_filters: 256
  pred_steps: 12
  n_negatives: 15
  offset: 16
