seed: null
gpu: null
data:
  path: /mnt/sting/hjyoon/projects/cross/HHAR/ActivityRecognitionExp/hhar_minmax_scaling_all.csv
  name: hhar
  class_type: gt
  domain_type: user
  save_cache: false
  load_cache: true
  cache_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/processed_hhar_minmax_scaling_all.pkl
multiprocessing:
  multiprocessing_distributed: true
  workers: 32
  world_size: 1
  rank: 0
  dist_url: tcp://localhost:10001
  dist_backend: nccl
train:
  optimizer: adam
  criterion: crossentropy
  resume: ""
  epochs: 100
  start_epoch: 0
  batch_size: 256
  lr: 0.0001
  fix_pred_lr: false
  weight_decay: 0.0001
  print_freq: 100
  save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/temp
model:
  type: cpc
  input_channels: 3
  z_dim: 256
  num_blocks: 5
  num_filters: 256
  pred_steps: 12
  n_negatives: 15
  offset: 16