### Default config
mode: pretrain
seed: 0
gpu: [2]
num_workers: 8
dist_url: tcp://localhost:10001
### Dataset config
dataset_name: ichar
train_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_PH0034-ykha/pretrain_target/train.pkl
test_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_PH0034-ykha/pretrain_target/val.pkl
val_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_PH0034-ykha/pretrain_target/val.pkl
input_channels: 3
num_cls: 9
### Training config
optimizer: adam
criterion: crossentropy
start_epoch: 0
epochs: 300
batch_size: 256
lr: 0.00005
momentum: 0.0
wd: 0.0
### Logs and checkpoints
resume: ''
ckpt_dir: /mnt/sting/hjyoon/projects/augcontrast/models/simclr_preliminary/simclr
log_freq: 20
save_freq: 10
### Model config
pretext: simclr
z_dim: 96
out_dim: 50
T: 0.1
mlp: true
freeze: false
neg_per_domain: false