data:
  dir: /mnt/sting/hjyoon/projects/cross/ImageNet_ILSVRC2012_mini

multiprocessing:
  workers: 32
  world_size: -1
  rank: -1
  dist_url: tcp://224.66.41.62:23456
  dist_backend: nccl
  seed: null
  gpu: null
  multiprocessing_distributed: true

training:
  arch: resnet18
  resume: ""
  epochs: 100
  start_epoch: 0
  batch_size: 512
  lr: 0.00001
  momentum: 0.9
  weight_decay: 1e-4

utilities:
  print_freq: 100
  save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/temp

augcontrast:
  temp: 0.07
  fix_pred_lr: false
