mode: finetune
num_workers: 1
dataset_name: ichar
test_dataset_path: overhead_samples/ichar_10shot_ph0007.pkl
input_channels: 3
num_cls: 9
optimizer: adam
criterion: crossentropy
start_epoch: 0
epochs: 20
batch_size: 4
lr: 0.005
wd: 0.0
task_per_domain: true
num_task: 8
multi_cond_num_task: 4
task_size: 128
task_lr: 0.005
reg_lambda: 0
log_meta_train: false
pretext: metacpc
enc_blocks: 4
kernel_sizes: [8, 4, 2, 1]
strides: [4, 2, 1, 1]
agg_blocks: 5
z_dim: 256
pooling: mean
pred_steps: 12
n_negatives: 15
offset: 4
neg_per_domain: false
mlp: false
freeze: true
domain_adaptation: true
out_cls_neg_sampling: false
task_steps: 10
no_vars: true
