mode: finetune
num_workers: 1
dataset_name: ichar
test_dataset_path: overhead_samples/ichar_10shot_ph0007.pkl
input_channels: 3
num_cls: 9
optimizer: adam
criterion: crossentropy
start_epoch: 0
epochs: 20
batch_size: 4
lr: 0.005
wd: 0.0
task_per_domain: true
num_task: 8
multi_cond_num_task: 4
task_size: 128
task_lr: 0.001
reg_lambda: 0
log_meta_train: false
pretrained_membank: ''
bank_size: 1024
membank_lr: 0.1
membank_optimizer: adam
membank_wd: 0.0
membank_m: 0.9
task_membank_lr: 1
pretext: metasimclr
out_dim: 50
T: 0.1
z_dim: 96
mlp: false
neg_per_domain: false
freeze: true
domain_adaptation: true
adapt_w_neg: true
out_cls_neg_sampling: false
task_steps: 10
no_vars: true
visualization: false
