seed: null
gpu: null
data:
  train_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_c_model_lgwatch/pretrain/train.pkl
  test_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_c_model_lgwatch/pretrain/test.pkl
  val_dataset_path: /mnt/sting/hjyoon/projects/cross/HHAR/augcon/target_user_c_model_lgwatch/pretrain/val.pkl
  name: hhar
multiprocessing:
  multiprocessing_distributed: true
  workers: 32
  world_size: 1
  rank: 0
  dist_url: tcp://localhost:10001
  dist_backend: nccl
train:
  optimizer: adam
  criterion: crossentropy
  resume: ""
  epochs: 100
  start_epoch: 0
  batch_size: 256
  lr: 0.0001
  fix_pred_lr: false
  weight_decay: 0.0001
  print_freq: 100
  save_dir: /mnt/sting/hjyoon/projects/augcontrast/models/pretrained/230418_target_user_c_model_lgwatch
  cos: false
  schedule: []
model:
  type: cpc
  input_channels: 3
  z_dim: 256
  num_blocks: 5
  num_filters: 256
  pred_steps: 12
  n_negatives: 15
  offset: 16
