### Default config
mode: finetune
seed: 0
gpu: [1]
num_workers: 4
dist_url: tcp://localhost:10001

### Dataset config
dataset_name: hhar
train_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/finetune/10shot/target/train.pkl
test_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/finetune/10shot/target/test.pkl
val_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_WA4697-jhryu/finetune/10shot/target/val.pkl
input_channels: 3
num_cls: 9

### Training config
optimizer: adam
criterion: crossentropy
start_epoch: 0
epochs: 50
batch_size: 4
lr: 0.001 # 0.0005
wd: 0.0

### Logs and checkpoints
resume: ''
pretrained: /mnt/sting/hjyoon/projects/augcontrast/models/0605_preliminary_global/pretrain/cpc_perdomain/checkpoint_0099.pth.tar
ckpt_dir: /mnt/sting/hjyoon/projects/augcontrast/models/0605_preliminary_global/finetune/cpc_random
log_freq: 5
save_freq: 10

### Model config
pretext: cpc
## Encoder
enc_blocks: 4
kernel_sizes: [8, 4, 4, 1]
strides: [4, 2, 2, 1]
## Aggregator
agg_blocks: 5
z_dim: 256
## Predictor
pooling: mean
pred_steps: 4
n_negatives: 15
offset: 4
neg_per_domain: false
mlp: true
freeze: true