### Default config
mode: finetune
seed: 0
gpu: [0]
num_workers: 4
dist_url: tcp://localhost:10001

### Dataset config
dataset_name: hhar
train_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_PH0007-jskim/finetune/10shot/target/train.pkl
test_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_PH0007-jskim/finetune/10shot/target/test.pkl
val_dataset_path: /mnt/sting/hjyoon/projects/cross/ICHAR/augcon/target_domain_PH0007-jskim/finetune/10shot/target/val.pkl
input_channels: 3
num_cls: 9

### Training config
optimizer: adam
criterion: crossentropy
start_epoch: 0
epochs: 50
batch_size: 4
lr: 0.001 # 0.0005
wd: 0.0

### Logs and checkpoints
resume: ''
pretrained: /mnt/sting/hjyoon/projects/augcontrast/models/0605_preliminary_global/pretrain/metacpc_random/checkpoint_0829.pth.tar
ckpt_dir: /mnt/sting/hjyoon/projects/augcontrast/models/0605_preliminary_global/finetune/metacpc_perdomain
log_freq: 30
save_freq: 10

### Model config
pretext: metacpc
## Encoder
enc_blocks: 4
kernel_sizes: [8, 4, 2, 1]
strides: [4, 2, 1, 1]
## Aggregator
agg_blocks: 4
z_dim: 256
## Predictor
pooling: mean
pred_steps: 4
n_negatives: 15
offset: 4
## Domain adaptation
domain_adaptation: true
task_steps: 10
task_lr: 0.005
## Classifier
mlp: false
freeze: true